spring:
  application:
    name: all-my-links
  datasource:
    url: jdbc:postgresql://localhost:15432/aml
    username: postgresql
    password: postgresql
  mail:
    host: localhost
    port: 2525
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${AUTH_GOOGLE_CLIENT_ID}
            client-secret: ${AUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${aml.base-url}/login/oauth2/code/google

aml:
  base-url: http://localhost:8080
  mail-service:
    from-email: robot@allmylinks.co.uk
    from-name: AML Robot
  file-service:
    backend: DISK
    disk-storage:
      base-path: ./storage
  image-service:
    allowed-types:
      - image/jpeg
      - image/png
    max-file-size-bytes: 10485760
  backoffice:
    defaults:
      admin-profile: abarmin
    channel: telegram
    telegram-configuration:
      bot-token: ${BACKOFFICE_BOT_TOKEN}
      admin-chat-id: ${BACKOFFICE_ADMIN_CHAT_ID}

logging:
  file:
    path: ./logs
#  level:
#    org:
#      springframework:
#        security: DEBUG
