spring:
  application:
    name: all-my-links
  datasource:
    url: jdbc:postgresql://localhost:15432/aml
    username: postgresql
    password: postgresql
  mail:
    host: localhost
    port: 2525
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aml:
  base-url: http://localhost:8080
  mail-service:
    from-email: robot@allmylinks.co.uk
    from-name: AML Robot
  file-service:
    backend: DISK
    disk-storage:
      base-path: ./storage
  image-service:
    allowed-types:
      - image/jpeg
      - image/png
    max-file-size-bytes: 10485760
  backoffice:
    adminEmail: robot@allmylinks.co.uk
    defaults:
      admin-profile: abarmin

logging:
  file:
    path: ./logs
#  level:
#    org:
#      springframework:
#        security: DEBUG
