import Box from "@mui/material/Box";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "1111 Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box sx={{ height: '100vh' }}>
      {children}
    </Box>
  );
}