version: '3.9'

services:
  db:
    image: postgres:17
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgresql
      POSTGRES_DB: aml
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

  mail:
    image: rnwood/smtp4dev
    ports:
      - 4000:80
      - 2525:25
