export interface StateChangeRequest {
  type: StateChangeRequestType;
}

export const enum StateChangeRequestType {
  PAGE_ADD = 'PAGE_ADD',
  PAGE_DELETE = 'PAGE_DELETE',
  PAGE_UPDATE = 'PAGE_UPDATE',
  PAGE_SELECT = 'PAGE_SELECT',

  BLOCK_ADD = 'BLOCK_ADD',
  BLOCK_SELECT = 'BLOCK_SELECT',
  BLOCK_UPDATE_PROPS = 'BLOCK_UPDATE_PROPS',
  BLOCK_MOVE_UP = 'BLOCK_MOVE_UP',
  BLOCK_MOVE_DOWN = 'BLOCK_MOVE_DOWN',
  BLOCK_DELETE = 'BLOCK_DELETE',

  LEFT_PANEL_CHANGE = 'LEFT_PANEL_CHANGE',

  DASHBOARD_LOAD_DATA = 'DASHBOARD_LOAD_DATA'
}