import "@/app/globals.css";
import { Box, CssVarsProvider } from "@mui/joy";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "1111 Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <CssVarsProvider>
      <Box sx={{ height: '100vh' }}>
        {children}
      </Box>
    </CssVarsProvider>
  );
}
